/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "../xnap_asn.1/XnAP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_PDUSessionResourcesActivityNotify-Item.h"

#include "ASN_XNAP_QoSFlowsActivityNotifyList.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item, pduSessionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PDUSession_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionId"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item, pduSessionLevelUPactivityreport),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UserPlaneTrafficActivityReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionLevelUPactivityreport"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item, qosFlowsActivityNotifyList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_QoSFlowsActivityNotifyList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowsActivityNotifyList"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pduSessionId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pduSessionLevelUPactivityreport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* qosFlowsActivityNotifyList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_specs_1 = {
	sizeof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item),
	offsetof(struct ASN_XNAP_PDUSessionResourcesActivityNotify_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item = {
	"PDUSessionResourcesActivityNotify-Item",
	"PDUSessionResourcesActivityNotify-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_1,
	4,	/* Elements count */
	&asn_SPC_ASN_XNAP_PDUSessionResourcesActivityNotify_Item_specs_1	/* Additional specs */
};

