/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_AreaOfInterest-Item.h"

#include "ASN_XNAP_ListOfTAIsinAoI.h"
#include "ASN_XNAP_ListOfCells.h"
#include "ASN_XNAP_ListOfRANNodesinAoI.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_AreaOfInterest_Item_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_AreaOfInterest_Item, listOfTAIsinAoI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ListOfTAIsinAoI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfTAIsinAoI"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_AreaOfInterest_Item, listOfCellsinAoI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ListOfCells,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfCellsinAoI"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_AreaOfInterest_Item, listOfRANNodesinAoI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ListOfRANNodesinAoI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listOfRANNodesinAoI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_AreaOfInterest_Item, requestReferenceID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RequestReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestReferenceID"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_AreaOfInterest_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_AreaOfInterest_Item_oms_1[] = { 0, 1, 2, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_AreaOfInterest_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfTAIsinAoI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfCellsinAoI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* listOfRANNodesinAoI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* requestReferenceID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_AreaOfInterest_Item_specs_1 = {
	sizeof(struct ASN_XNAP_AreaOfInterest_Item),
	offsetof(struct ASN_XNAP_AreaOfInterest_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_AreaOfInterest_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_AreaOfInterest_Item_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_AreaOfInterest_Item = {
	"AreaOfInterest-Item",
	"AreaOfInterest-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_AreaOfInterest_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_AreaOfInterest_Item_1,
	5,	/* Elements count */
	&asn_SPC_ASN_XNAP_AreaOfInterest_Item_specs_1	/* Additional specs */
};

