/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_NRDL_ULTransmissionPeriodicity_H_
#define	_ASN_XNAP_NRDL_ULTransmissionPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_NRDL_ULTransmissionPeriodicity {
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms0p5	= 0,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms0p625	= 1,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms1	= 2,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms1p25	= 3,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms2	= 4,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms2p5	= 5,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms3	= 6,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms4	= 7,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms5	= 8,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms10	= 9,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms20	= 10,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms40	= 11,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms60	= 12,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms80	= 13,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms100	= 14,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms120	= 15,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms140	= 16,
	ASN_XNAP_NRDL_ULTransmissionPeriodicity_ms160	= 17
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_NRDL_ULTransmissionPeriodicity;

/* ASN_XNAP_NRDL-ULTransmissionPeriodicity */
typedef long	 ASN_XNAP_NRDL_ULTransmissionPeriodicity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_NRDL_ULTransmissionPeriodicity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NRDL_ULTransmissionPeriodicity;
extern const asn_INTEGER_specifics_t asn_SPC_NRDL_ULTransmissionPeriodicity_specs_1;
asn_struct_free_f NRDL_ULTransmissionPeriodicity_free;
asn_struct_print_f NRDL_ULTransmissionPeriodicity_print;
asn_constr_check_f NRDL_ULTransmissionPeriodicity_constraint;
ber_type_decoder_f NRDL_ULTransmissionPeriodicity_decode_ber;
der_type_encoder_f NRDL_ULTransmissionPeriodicity_encode_der;
xer_type_decoder_f NRDL_ULTransmissionPeriodicity_decode_xer;
xer_type_encoder_f NRDL_ULTransmissionPeriodicity_encode_xer;
oer_type_decoder_f NRDL_ULTransmissionPeriodicity_decode_oer;
oer_type_encoder_f NRDL_ULTransmissionPeriodicity_encode_oer;
per_type_decoder_f NRDL_ULTransmissionPeriodicity_decode_uper;
per_type_encoder_f NRDL_ULTransmissionPeriodicity_encode_uper;
per_type_decoder_f NRDL_ULTransmissionPeriodicity_decode_aper;
per_type_encoder_f NRDL_ULTransmissionPeriodicity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_NRDL_ULTransmissionPeriodicity_H_ */
#include <asn_internal.h>
