/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "../xnap_asn.1/XnAP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_SplitSRB_RRCTransfer_H_
#define	_ASN_XNAP_SplitSRB_RRCTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeEnumerated.h>
#include "ASN_XNAP_DeliveryStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_SplitSRB_RRCTransfer__srbType {
	ASN_XNAP_SplitSRB_RRCTransfer__srbType_srb1	= 0,
	ASN_XNAP_SplitSRB_RRCTransfer__srbType_srb2	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_SplitSRB_RRCTransfer__srbType;

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* ASN_XNAP_SplitSRB-RRCTransfer */
typedef struct ASN_XNAP_SplitSRB_RRCTransfer {
	OCTET_STRING_t	*rrcContainer;	/* OPTIONAL */
	long	 srbType;
	ASN_XNAP_DeliveryStatus_t	*deliveryStatus;	/* OPTIONAL */
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_SplitSRB_RRCTransfer_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_srbType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SplitSRB_RRCTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SplitSRB_RRCTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_SplitSRB_RRCTransfer_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_SplitSRB_RRCTransfer_H_ */
#include <asn_internal.h>
