/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_FiveGProSeAuthorized.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_FiveGProSeAuthorized_1[] = {
	{ ATF_POINTER, 6, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, fiveGproSeDirectDiscovery),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_FiveGProSeDirectDiscovery,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fiveGproSeDirectDiscovery"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, fiveGproSeDirectCommunication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_FiveGProSeDirectCommunication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fiveGproSeDirectCommunication"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, fiveGnrProSeLayer2UEtoNetworkRelay),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_FiveGProSeLayer2UEtoNetworkRelay,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fiveGnrProSeLayer2UEtoNetworkRelay"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, fiveGnrProSeLayer3UEtoNetworkRelay),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_FiveGProSeLayer3UEtoNetworkRelay,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fiveGnrProSeLayer3UEtoNetworkRelay"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, fiveGnrProSeLayer2RemoteUE),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_FiveGProSeLayer2RemoteUE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fiveGnrProSeLayer2RemoteUE"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_FiveGProSeAuthorized, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P106,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_FiveGProSeAuthorized_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_FiveGProSeAuthorized_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fiveGproSeDirectDiscovery */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* fiveGproSeDirectCommunication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* fiveGnrProSeLayer2UEtoNetworkRelay */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* fiveGnrProSeLayer3UEtoNetworkRelay */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* fiveGnrProSeLayer2RemoteUE */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_FiveGProSeAuthorized_specs_1 = {
	sizeof(struct ASN_XNAP_FiveGProSeAuthorized),
	offsetof(struct ASN_XNAP_FiveGProSeAuthorized, _asn_ctx),
	asn_MAP_ASN_XNAP_FiveGProSeAuthorized_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_FiveGProSeAuthorized_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_FiveGProSeAuthorized = {
	"FiveGProSeAuthorized",
	"FiveGProSeAuthorized",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1,
	sizeof(asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_FiveGProSeAuthorized_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_FiveGProSeAuthorized_1,
	6,	/* Elements count */
	&asn_SPC_ASN_XNAP_FiveGProSeAuthorized_specs_1	/* Additional specs */
};

