/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_EUTRAPaging_eDRX_Cycle_H_
#define	_ASN_XNAP_EUTRAPaging_eDRX_Cycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_EUTRAPaging_eDRX_Cycle {
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hfhalf	= 0,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf1	= 1,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf2	= 2,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf4	= 3,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf6	= 4,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf8	= 5,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf10	= 6,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf12	= 7,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf14	= 8,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf16	= 9,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf32	= 10,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf64	= 11,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf128	= 12,
	ASN_XNAP_EUTRAPaging_eDRX_Cycle_hf256	= 13
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_EUTRAPaging_eDRX_Cycle;

/* ASN_XNAP_EUTRAPaging-eDRX-Cycle */
typedef long	 ASN_XNAP_EUTRAPaging_eDRX_Cycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_EUTRAPaging_eDRX_Cycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_EUTRAPaging_eDRX_Cycle;
extern const asn_INTEGER_specifics_t asn_SPC_EUTRAPaging_eDRX_Cycle_specs_1;
asn_struct_free_f EUTRAPaging_eDRX_Cycle_free;
asn_struct_print_f EUTRAPaging_eDRX_Cycle_print;
asn_constr_check_f EUTRAPaging_eDRX_Cycle_constraint;
ber_type_decoder_f EUTRAPaging_eDRX_Cycle_decode_ber;
der_type_encoder_f EUTRAPaging_eDRX_Cycle_encode_der;
xer_type_decoder_f EUTRAPaging_eDRX_Cycle_decode_xer;
xer_type_encoder_f EUTRAPaging_eDRX_Cycle_encode_xer;
oer_type_decoder_f EUTRAPaging_eDRX_Cycle_decode_oer;
oer_type_encoder_f EUTRAPaging_eDRX_Cycle_encode_oer;
per_type_decoder_f EUTRAPaging_eDRX_Cycle_decode_uper;
per_type_encoder_f EUTRAPaging_eDRX_Cycle_encode_uper;
per_type_decoder_f EUTRAPaging_eDRX_Cycle_decode_aper;
per_type_encoder_f EUTRAPaging_eDRX_Cycle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_EUTRAPaging_eDRX_Cycle_H_ */
#include <asn_internal.h>
