/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_SensorName.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_uncompensatedBarometricConfig_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_uncompensatedBarometricConfig_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_ueSpeedConfig_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_ueSpeedConfig_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_ueOrientationConfig_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_ueOrientationConfig_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_uncompensatedBarometricConfig_value2enum_2[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_uncompensatedBarometricConfig_enum2value_2[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_uncompensatedBarometricConfig_specs_2 = {
	asn_MAP_ASN_XNAP_uncompensatedBarometricConfig_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_uncompensatedBarometricConfig_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_2 = {
	"uncompensatedBarometricConfig",
	"uncompensatedBarometricConfig",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2,
	sizeof(asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_tags_2[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_uncompensatedBarometricConfig_constr_2, &asn_PER_type_ASN_XNAP_uncompensatedBarometricConfig_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_uncompensatedBarometricConfig_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_ueSpeedConfig_value2enum_5[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_ueSpeedConfig_enum2value_5[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_ueSpeedConfig_specs_5 = {
	asn_MAP_ASN_XNAP_ueSpeedConfig_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_ueSpeedConfig_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_ueSpeedConfig_5 = {
	"ueSpeedConfig",
	"ueSpeedConfig",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5,
	sizeof(asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5)
		/sizeof(asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5)
		/sizeof(asn_DEF_ASN_XNAP_ueSpeedConfig_tags_5[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_ueSpeedConfig_constr_5, &asn_PER_type_ASN_XNAP_ueSpeedConfig_constr_5, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_ueSpeedConfig_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_ueOrientationConfig_value2enum_8[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_ueOrientationConfig_enum2value_8[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_ueOrientationConfig_specs_8 = {
	asn_MAP_ASN_XNAP_ueOrientationConfig_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_ueOrientationConfig_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_ueOrientationConfig_8 = {
	"ueOrientationConfig",
	"ueOrientationConfig",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8,
	sizeof(asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8)
		/sizeof(asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8)
		/sizeof(asn_DEF_ASN_XNAP_ueOrientationConfig_tags_8[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_ueOrientationConfig_constr_8, &asn_PER_type_ASN_XNAP_ueOrientationConfig_constr_8, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_ueOrientationConfig_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_SensorName_1[] = {
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_SensorName, uncompensatedBarometricConfig),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_uncompensatedBarometricConfig_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uncompensatedBarometricConfig"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_SensorName, ueSpeedConfig),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ueSpeedConfig_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueSpeedConfig"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_SensorName, ueOrientationConfig),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ueOrientationConfig_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueOrientationConfig"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_SensorName, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P319,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_SensorName_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_SensorName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SensorName_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uncompensatedBarometricConfig */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ueSpeedConfig */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ueOrientationConfig */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SensorName_specs_1 = {
	sizeof(struct ASN_XNAP_SensorName),
	offsetof(struct ASN_XNAP_SensorName, _asn_ctx),
	asn_MAP_ASN_XNAP_SensorName_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_SensorName_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SensorName = {
	"SensorName",
	"SensorName",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_SensorName_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SensorName_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SensorName_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SensorName_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SensorName_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SensorName_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_SensorName_1,
	4,	/* Elements count */
	&asn_SPC_ASN_XNAP_SensorName_specs_1	/* Additional specs */
};

