/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-Containers"
 * 	found in "../xnap_asn.1/XnAP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_PrivateIE_Field_H_
#define	_ASN_XNAP_PrivateIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_PrivateIE-ID.h"
#include "ASN_XNAP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_PrivateMessage_IEs__value_PR {
	ASN_XNAP_PrivateMessage_IEs__value_PR_NOTHING	/* No components present */
	
} ASN_XNAP_PrivateMessage_IEs__value_PR;

/* ASN_XNAP_PrivateIE-Field */
typedef struct ASN_XNAP_PrivateMessage_IEs {
	ASN_XNAP_PrivateIE_ID_t	 id;
	ASN_XNAP_Criticality_t	 criticality;
	struct ASN_XNAP_PrivateMessage_IEs__value {
		ASN_XNAP_PrivateMessage_IEs__value_PR present;
		union ASN_XNAP_PrivateMessage_IEs__ASN_XNAP_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_PrivateMessage_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_PrivateMessage_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_PrivateMessage_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_PrivateMessage_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_PrivateIE_Field_H_ */
#include <asn_internal.h>
