/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_MDT-Configuration-NR.h"

#include "ASN_XNAP_AreaScopeOfMDT-NR.h"
#include "ASN_XNAP_MDTPLMNList.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_MDT_Configuration_NR_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_MDT_Configuration_NR, mdt_Activation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_MDT_Activation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mdt-Activation"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_MDT_Configuration_NR, areaScopeOfMDT_NR),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_AreaScopeOfMDT_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaScopeOfMDT-NR"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_MDT_Configuration_NR, mDTMode_NR),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_MDTMode_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mDTMode-NR"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_MDT_Configuration_NR, signallingBasedMDTPLMNList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_MDTPLMNList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signallingBasedMDTPLMNList"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_MDT_Configuration_NR, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P169,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_MDT_Configuration_NR_oms_1[] = { 1, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_MDT_Configuration_NR_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mdt-Activation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* areaScopeOfMDT-NR */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mDTMode-NR */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* signallingBasedMDTPLMNList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_MDT_Configuration_NR_specs_1 = {
	sizeof(struct ASN_XNAP_MDT_Configuration_NR),
	offsetof(struct ASN_XNAP_MDT_Configuration_NR, _asn_ctx),
	asn_MAP_ASN_XNAP_MDT_Configuration_NR_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_MDT_Configuration_NR_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_MDT_Configuration_NR = {
	"MDT-Configuration-NR",
	"MDT-Configuration-NR",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1,
	sizeof(asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_MDT_Configuration_NR_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_MDT_Configuration_NR_1,
	5,	/* Elements count */
	&asn_SPC_ASN_XNAP_MDT_Configuration_NR_specs_1	/* Additional specs */
};

