/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-Containers"
 * 	found in "../xnap_asn.1/XnAP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_ProtocolIE_ContainerPairList_H_
#define	_ASN_XNAP_ProtocolIE_ContainerPairList_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_ProtocolIE_ContainerPairList_H_ */
#include <asn_internal.h>
