/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_ProtectedE-UTRAResource-Item.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 84)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_XNAP_protectedFootprintFrequencyPattern_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size >= 6 && size <= 110)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ASN_XNAP_resourceType_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_resourceType_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  84,  84 }	/* (SIZE(84..84,...)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_protectedFootprintFrequencyPattern_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_protectedFootprintFrequencyPattern_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  7,  7,  6,  110 }	/* (SIZE(6..110,...)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_resourceType_value2enum_2[] = {
	{ 0,	14,	"downlinknonCRS" },
	{ 1,	3,	"cRS" },
	{ 2,	6,	"uplink" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_resourceType_enum2value_2[] = {
	1,	/* cRS(1) */
	0,	/* downlinknonCRS(0) */
	2	/* uplink(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_resourceType_specs_2 = {
	asn_MAP_ASN_XNAP_resourceType_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_resourceType_enum2value_2,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_resourceType_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_resourceType_2 = {
	"resourceType",
	"resourceType",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_resourceType_tags_2,
	sizeof(asn_DEF_ASN_XNAP_resourceType_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_resourceType_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_resourceType_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_resourceType_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_resourceType_tags_2[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_resourceType_constr_2, &asn_PER_type_ASN_XNAP_resourceType_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_resourceType_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_ProtectedE_UTRAResource_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, resourceType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_resourceType_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resourceType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, intra_PRBProtectedResourceFootprint),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constr_7, &asn_PER_memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constr_7,  memb_ASN_XNAP_intra_PRBProtectedResourceFootprint_constraint_1 },
		0, 0, /* No default value */
		"intra-PRBProtectedResourceFootprint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, protectedFootprintFrequencyPattern),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_ASN_XNAP_protectedFootprintFrequencyPattern_constr_8, &asn_PER_memb_ASN_XNAP_protectedFootprintFrequencyPattern_constr_8,  memb_ASN_XNAP_protectedFootprintFrequencyPattern_constraint_1 },
		0, 0, /* No default value */
		"protectedFootprintFrequencyPattern"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, protectedFootprintTimePattern),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtectedE_UTRAFootprintTimePattern,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protectedFootprintTimePattern"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P273,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_ProtectedE_UTRAResource_Item_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_ProtectedE_UTRAResource_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* resourceType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* intra-PRBProtectedResourceFootprint */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* protectedFootprintFrequencyPattern */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* protectedFootprintTimePattern */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_ProtectedE_UTRAResource_Item_specs_1 = {
	sizeof(struct ASN_XNAP_ProtectedE_UTRAResource_Item),
	offsetof(struct ASN_XNAP_ProtectedE_UTRAResource_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_ProtectedE_UTRAResource_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_ProtectedE_UTRAResource_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item = {
	"ProtectedE-UTRAResource-Item",
	"ProtectedE-UTRAResource-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_ProtectedE_UTRAResource_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_ProtectedE_UTRAResource_Item_1,
	5,	/* Elements count */
	&asn_SPC_ASN_XNAP_ProtectedE_UTRAResource_Item_specs_1	/* Additional specs */
};

