/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_PDUSessionResourcesToBeSetup-Item.h"

#include "ASN_XNAP_PDUSessionAggregateMaximumBitRate.h"
#include "ASN_XNAP_UPTransportLayerInformation.h"
#include "ASN_XNAP_SecurityIndication.h"
#include "ASN_XNAP_DataforwardingandOffloadingInfofromSource.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, pduSessionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PDUSession_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, s_NSSAI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_S_NSSAI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s-NSSAI"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, pduSessionAMBR),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PDUSessionAggregateMaximumBitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionAMBR"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, uL_NG_U_TNLatUPF),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-NG-U-TNLatUPF"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, source_DL_NG_U_TNL_Information),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"source-DL-NG-U-TNL-Information"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, securityIndication),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_SecurityIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, pduSessionType),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PDUSessionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionType"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, pduSessionNetworkInstance),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_PDUSessionNetworkInstance,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pduSessionNetworkInstance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, qosFlowsToBeSetup_List),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_QoSFlowsToBeSetup_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowsToBeSetup-List"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, dataforwardinginfofromSource),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DataforwardingandOffloadingInfofromSource,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataforwardinginfofromSource"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P231,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_oms_1[] = { 2, 4, 5, 7, 9, 10 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pduSessionId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* s-NSSAI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pduSessionAMBR */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uL-NG-U-TNLatUPF */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* source-DL-NG-U-TNL-Information */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* securityIndication */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* pduSessionType */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* pduSessionNetworkInstance */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* qosFlowsToBeSetup-List */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* dataforwardinginfofromSource */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_specs_1 = {
	sizeof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item),
	offsetof(struct ASN_XNAP_PDUSessionResourcesToBeSetup_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tag2el_1,
	11,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	11,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item = {
	"PDUSessionResourcesToBeSetup-Item",
	"PDUSessionResourcesToBeSetup-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_1,
	11,	/* Elements count */
	&asn_SPC_ASN_XNAP_PDUSessionResourcesToBeSetup_Item_specs_1	/* Additional specs */
};

