/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_AreaScopeOfMDT_EUTRA_H_
#define	_ASN_XNAP_AreaScopeOfMDT_EUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_AreaScopeOfMDT_EUTRA_PR {
	ASN_XNAP_AreaScopeOfMDT_EUTRA_PR_NOTHING,	/* No components present */
	ASN_XNAP_AreaScopeOfMDT_EUTRA_PR_cellBased,
	ASN_XNAP_AreaScopeOfMDT_EUTRA_PR_tABased,
	ASN_XNAP_AreaScopeOfMDT_EUTRA_PR_tAIBased
	/* Extensions may appear below */
	
} ASN_XNAP_AreaScopeOfMDT_EUTRA_PR;

/* Forward declarations */
struct ASN_XNAP_CellBasedMDT_EUTRA;
struct ASN_XNAP_TABasedMDT;
struct ASN_XNAP_TAIBasedMDT;

/* ASN_XNAP_AreaScopeOfMDT-EUTRA */
typedef struct ASN_XNAP_AreaScopeOfMDT_EUTRA {
	ASN_XNAP_AreaScopeOfMDT_EUTRA_PR present;
	union ASN_XNAP_AreaScopeOfMDT_EUTRA_u {
		struct ASN_XNAP_CellBasedMDT_EUTRA	*cellBased;
		struct ASN_XNAP_TABasedMDT	*tABased;
		struct ASN_XNAP_TAIBasedMDT	*tAIBased;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_AreaScopeOfMDT_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_AreaScopeOfMDT_EUTRA;
extern asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_AreaScopeOfMDT_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_AreaScopeOfMDT_EUTRA_1[3];
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_AreaScopeOfMDT_EUTRA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_AreaScopeOfMDT_EUTRA_H_ */
#include <asn_internal.h>
