/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_NE-DC-TDM-Pattern.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_ASN_XNAP_harqOffset_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ASN_XNAP_subframeAssignment_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_subframeAssignment_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_harqOffset_constr_10 CC_NOTUSED = {
	{ 1, 1 }	/* (0..9) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_harqOffset_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_subframeAssignment_value2enum_2[] = {
	{ 0,	3,	"sa0" },
	{ 1,	3,	"sa1" },
	{ 2,	3,	"sa2" },
	{ 3,	3,	"sa3" },
	{ 4,	3,	"sa4" },
	{ 5,	3,	"sa5" },
	{ 6,	3,	"sa6" }
};
static const unsigned int asn_MAP_ASN_XNAP_subframeAssignment_enum2value_2[] = {
	0,	/* sa0(0) */
	1,	/* sa1(1) */
	2,	/* sa2(2) */
	3,	/* sa3(3) */
	4,	/* sa4(4) */
	5,	/* sa5(5) */
	6	/* sa6(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_subframeAssignment_specs_2 = {
	asn_MAP_ASN_XNAP_subframeAssignment_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_subframeAssignment_enum2value_2,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_subframeAssignment_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_subframeAssignment_2 = {
	"subframeAssignment",
	"subframeAssignment",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_subframeAssignment_tags_2,
	sizeof(asn_DEF_ASN_XNAP_subframeAssignment_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_subframeAssignment_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_subframeAssignment_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_subframeAssignment_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_subframeAssignment_tags_2[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_subframeAssignment_constr_2, &asn_PER_type_ASN_XNAP_subframeAssignment_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_subframeAssignment_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_NE_DC_TDM_Pattern_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_NE_DC_TDM_Pattern, subframeAssignment),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_subframeAssignment_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subframeAssignment"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_NE_DC_TDM_Pattern, harqOffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ASN_XNAP_harqOffset_constr_10, &asn_PER_memb_ASN_XNAP_harqOffset_constr_10,  memb_ASN_XNAP_harqOffset_constraint_1 },
		0, 0, /* No default value */
		"harqOffset"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_NE_DC_TDM_Pattern, iE_Extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P183,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extension"
		},
};
static const int asn_MAP_ASN_XNAP_NE_DC_TDM_Pattern_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_NE_DC_TDM_Pattern_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* subframeAssignment */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* harqOffset */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extension */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_NE_DC_TDM_Pattern_specs_1 = {
	sizeof(struct ASN_XNAP_NE_DC_TDM_Pattern),
	offsetof(struct ASN_XNAP_NE_DC_TDM_Pattern, _asn_ctx),
	asn_MAP_ASN_XNAP_NE_DC_TDM_Pattern_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_NE_DC_TDM_Pattern_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern = {
	"NE-DC-TDM-Pattern",
	"NE-DC-TDM-Pattern",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1,
	sizeof(asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NE_DC_TDM_Pattern_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_NE_DC_TDM_Pattern_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_NE_DC_TDM_Pattern_specs_1	/* Additional specs */
};

