/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_AllocationandRetentionPriority_H_
#define	_ASN_XNAP_AllocationandRetentionPriority_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_AllocationandRetentionPriority__pre_emption_capability {
	ASN_XNAP_AllocationandRetentionPriority__pre_emption_capability_shall_not_trigger_preemption	= 0,
	ASN_XNAP_AllocationandRetentionPriority__pre_emption_capability_may_trigger_preemption	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_AllocationandRetentionPriority__pre_emption_capability;
typedef enum ASN_XNAP_AllocationandRetentionPriority__pre_emption_vulnerability {
	ASN_XNAP_AllocationandRetentionPriority__pre_emption_vulnerability_not_preemptable	= 0,
	ASN_XNAP_AllocationandRetentionPriority__pre_emption_vulnerability_preemptable	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_AllocationandRetentionPriority__pre_emption_vulnerability;

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* ASN_XNAP_AllocationandRetentionPriority */
typedef struct ASN_XNAP_AllocationandRetentionPriority {
	long	 priorityLevel;
	long	 pre_emption_capability;
	long	 pre_emption_vulnerability;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_AllocationandRetentionPriority_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_pre_emption_capability_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_pre_emption_vulnerability_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_AllocationandRetentionPriority;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_AllocationandRetentionPriority_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_AllocationandRetentionPriority_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_AllocationandRetentionPriority_H_ */
#include <asn_internal.h>
