/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_H_
#define	_ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_NBIoT_UL_DL_AlignmentOffset {
	ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_khz_7dot5	= 0,
	ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_khz0	= 1,
	ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_khz7dot5	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_NBIoT_UL_DL_AlignmentOffset;

/* ASN_XNAP_NBIoT-UL-DL-AlignmentOffset */
typedef long	 ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NBIoT_UL_DL_AlignmentOffset;
extern const asn_INTEGER_specifics_t asn_SPC_NBIoT_UL_DL_AlignmentOffset_specs_1;
asn_struct_free_f NBIoT_UL_DL_AlignmentOffset_free;
asn_struct_print_f NBIoT_UL_DL_AlignmentOffset_print;
asn_constr_check_f NBIoT_UL_DL_AlignmentOffset_constraint;
ber_type_decoder_f NBIoT_UL_DL_AlignmentOffset_decode_ber;
der_type_encoder_f NBIoT_UL_DL_AlignmentOffset_encode_der;
xer_type_decoder_f NBIoT_UL_DL_AlignmentOffset_decode_xer;
xer_type_encoder_f NBIoT_UL_DL_AlignmentOffset_encode_xer;
oer_type_decoder_f NBIoT_UL_DL_AlignmentOffset_decode_oer;
oer_type_encoder_f NBIoT_UL_DL_AlignmentOffset_encode_oer;
per_type_decoder_f NBIoT_UL_DL_AlignmentOffset_decode_uper;
per_type_encoder_f NBIoT_UL_DL_AlignmentOffset_encode_uper;
per_type_decoder_f NBIoT_UL_DL_AlignmentOffset_decode_aper;
per_type_encoder_f NBIoT_UL_DL_AlignmentOffset_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_NBIoT_UL_DL_AlignmentOffset_H_ */
#include <asn_internal.h>
