/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_EUTRAPaging_Time_Window_H_
#define	_ASN_XNAP_EUTRAPaging_Time_Window_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_EUTRAPaging_Time_Window {
	ASN_XNAP_EUTRAPaging_Time_Window_s1	= 0,
	ASN_XNAP_EUTRAPaging_Time_Window_s2	= 1,
	ASN_XNAP_EUTRAPaging_Time_Window_s3	= 2,
	ASN_XNAP_EUTRAPaging_Time_Window_s4	= 3,
	ASN_XNAP_EUTRAPaging_Time_Window_s5	= 4,
	ASN_XNAP_EUTRAPaging_Time_Window_s6	= 5,
	ASN_XNAP_EUTRAPaging_Time_Window_s7	= 6,
	ASN_XNAP_EUTRAPaging_Time_Window_s8	= 7,
	ASN_XNAP_EUTRAPaging_Time_Window_s9	= 8,
	ASN_XNAP_EUTRAPaging_Time_Window_s10	= 9,
	ASN_XNAP_EUTRAPaging_Time_Window_s11	= 10,
	ASN_XNAP_EUTRAPaging_Time_Window_s12	= 11,
	ASN_XNAP_EUTRAPaging_Time_Window_s13	= 12,
	ASN_XNAP_EUTRAPaging_Time_Window_s14	= 13,
	ASN_XNAP_EUTRAPaging_Time_Window_s15	= 14,
	ASN_XNAP_EUTRAPaging_Time_Window_s16	= 15
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_EUTRAPaging_Time_Window;

/* ASN_XNAP_EUTRAPaging-Time-Window */
typedef long	 ASN_XNAP_EUTRAPaging_Time_Window_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_EUTRAPaging_Time_Window_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_EUTRAPaging_Time_Window;
extern const asn_INTEGER_specifics_t asn_SPC_EUTRAPaging_Time_Window_specs_1;
asn_struct_free_f EUTRAPaging_Time_Window_free;
asn_struct_print_f EUTRAPaging_Time_Window_print;
asn_constr_check_f EUTRAPaging_Time_Window_constraint;
ber_type_decoder_f EUTRAPaging_Time_Window_decode_ber;
der_type_encoder_f EUTRAPaging_Time_Window_encode_der;
xer_type_decoder_f EUTRAPaging_Time_Window_decode_xer;
xer_type_encoder_f EUTRAPaging_Time_Window_encode_xer;
oer_type_decoder_f EUTRAPaging_Time_Window_decode_oer;
oer_type_encoder_f EUTRAPaging_Time_Window_encode_oer;
per_type_decoder_f EUTRAPaging_Time_Window_decode_uper;
per_type_encoder_f EUTRAPaging_Time_Window_encode_uper;
per_type_decoder_f EUTRAPaging_Time_Window_decode_aper;
per_type_encoder_f EUTRAPaging_Time_Window_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_EUTRAPaging_Time_Window_H_ */
#include <asn_internal.h>
