/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_AreaScopeOfMDT-NR.h"

#include "ASN_XNAP_CellBasedMDT-NR.h"
#include "ASN_XNAP_TABasedMDT.h"
#include "ASN_XNAP_TAIBasedMDT.h"
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_AreaScopeOfMDT_NR_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ASN_XNAP_AreaScopeOfMDT_NR_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_XNAP_AreaScopeOfMDT_NR_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_AreaScopeOfMDT_NR, choice.cellBased),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_CellBasedMDT_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellBased"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_AreaScopeOfMDT_NR, choice.tABased),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_TABasedMDT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tABased"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_AreaScopeOfMDT_NR, choice.tAIBased),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_TAIBasedMDT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAIBased"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_AreaScopeOfMDT_NR_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellBased */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tABased */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* tAIBased */
};
asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_AreaScopeOfMDT_NR_specs_1 = {
	sizeof(struct ASN_XNAP_AreaScopeOfMDT_NR),
	offsetof(struct ASN_XNAP_AreaScopeOfMDT_NR, _asn_ctx),
	offsetof(struct ASN_XNAP_AreaScopeOfMDT_NR, present),
	sizeof(((struct ASN_XNAP_AreaScopeOfMDT_NR *)0)->present),
	asn_MAP_ASN_XNAP_AreaScopeOfMDT_NR_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_AreaScopeOfMDT_NR = {
	"AreaScopeOfMDT-NR",
	"AreaScopeOfMDT-NR",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ASN_XNAP_AreaScopeOfMDT_NR_constr_1, &asn_PER_type_ASN_XNAP_AreaScopeOfMDT_NR_constr_1, CHOICE_constraint },
	asn_MBR_ASN_XNAP_AreaScopeOfMDT_NR_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_AreaScopeOfMDT_NR_specs_1	/* Additional specs */
};

