/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_SecurityResult.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_integrityProtectionResult_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_integrityProtectionResult_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_confidentialityProtectionResult_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_confidentialityProtectionResult_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_integrityProtectionResult_value2enum_2[] = {
	{ 0,	9,	"performed" },
	{ 1,	13,	"not-performed" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_integrityProtectionResult_enum2value_2[] = {
	1,	/* not-performed(1) */
	0	/* performed(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_integrityProtectionResult_specs_2 = {
	asn_MAP_ASN_XNAP_integrityProtectionResult_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_integrityProtectionResult_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_integrityProtectionResult_2 = {
	"integrityProtectionResult",
	"integrityProtectionResult",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2,
	sizeof(asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2)
		/sizeof(asn_DEF_ASN_XNAP_integrityProtectionResult_tags_2[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_integrityProtectionResult_constr_2, &asn_PER_type_ASN_XNAP_integrityProtectionResult_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_integrityProtectionResult_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_confidentialityProtectionResult_value2enum_6[] = {
	{ 0,	9,	"performed" },
	{ 1,	13,	"not-performed" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_confidentialityProtectionResult_enum2value_6[] = {
	1,	/* not-performed(1) */
	0	/* performed(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_confidentialityProtectionResult_specs_6 = {
	asn_MAP_ASN_XNAP_confidentialityProtectionResult_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_confidentialityProtectionResult_enum2value_6,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_confidentialityProtectionResult_6 = {
	"confidentialityProtectionResult",
	"confidentialityProtectionResult",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6,
	sizeof(asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6)
		/sizeof(asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6)
		/sizeof(asn_DEF_ASN_XNAP_confidentialityProtectionResult_tags_6[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_confidentialityProtectionResult_constr_6, &asn_PER_type_ASN_XNAP_confidentialityProtectionResult_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_confidentialityProtectionResult_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_SecurityResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SecurityResult, integrityProtectionResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_integrityProtectionResult_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"integrityProtectionResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SecurityResult, confidentialityProtectionResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_confidentialityProtectionResult_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confidentialityProtectionResult"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_SecurityResult, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P317,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_SecurityResult_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_SecurityResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SecurityResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* integrityProtectionResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* confidentialityProtectionResult */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SecurityResult_specs_1 = {
	sizeof(struct ASN_XNAP_SecurityResult),
	offsetof(struct ASN_XNAP_SecurityResult, _asn_ctx),
	asn_MAP_ASN_XNAP_SecurityResult_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_SecurityResult_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SecurityResult = {
	"SecurityResult",
	"SecurityResult",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_SecurityResult_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SecurityResult_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SecurityResult_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SecurityResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SecurityResult_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SecurityResult_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_SecurityResult_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_SecurityResult_specs_1	/* Additional specs */
};

