/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_NRNRB_H_
#define	_ASN_XNAP_NRNRB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_NRNRB {
	ASN_XNAP_NRNRB_nrb11	= 0,
	ASN_XNAP_NRNRB_nrb18	= 1,
	ASN_XNAP_NRNRB_nrb24	= 2,
	ASN_XNAP_NRNRB_nrb25	= 3,
	ASN_XNAP_NRNRB_nrb31	= 4,
	ASN_XNAP_NRNRB_nrb32	= 5,
	ASN_XNAP_NRNRB_nrb38	= 6,
	ASN_XNAP_NRNRB_nrb51	= 7,
	ASN_XNAP_NRNRB_nrb52	= 8,
	ASN_XNAP_NRNRB_nrb65	= 9,
	ASN_XNAP_NRNRB_nrb66	= 10,
	ASN_XNAP_NRNRB_nrb78	= 11,
	ASN_XNAP_NRNRB_nrb79	= 12,
	ASN_XNAP_NRNRB_nrb93	= 13,
	ASN_XNAP_NRNRB_nrb106	= 14,
	ASN_XNAP_NRNRB_nrb107	= 15,
	ASN_XNAP_NRNRB_nrb121	= 16,
	ASN_XNAP_NRNRB_nrb132	= 17,
	ASN_XNAP_NRNRB_nrb133	= 18,
	ASN_XNAP_NRNRB_nrb135	= 19,
	ASN_XNAP_NRNRB_nrb160	= 20,
	ASN_XNAP_NRNRB_nrb162	= 21,
	ASN_XNAP_NRNRB_nrb189	= 22,
	ASN_XNAP_NRNRB_nrb216	= 23,
	ASN_XNAP_NRNRB_nrb217	= 24,
	ASN_XNAP_NRNRB_nrb245	= 25,
	ASN_XNAP_NRNRB_nrb264	= 26,
	ASN_XNAP_NRNRB_nrb270	= 27,
	ASN_XNAP_NRNRB_nrb273	= 28,
	/*
	 * Enumeration is extensible
	 */
	ASN_XNAP_NRNRB_nrb33	= 29,
	ASN_XNAP_NRNRB_nrb62	= 30,
	ASN_XNAP_NRNRB_nrb124	= 31,
	ASN_XNAP_NRNRB_nrb148	= 32,
	ASN_XNAP_NRNRB_nrb248	= 33
} e_ASN_XNAP_NRNRB;

/* ASN_XNAP_NRNRB */
typedef long	 ASN_XNAP_NRNRB_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_NRNRB_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NRNRB;
extern const asn_INTEGER_specifics_t asn_SPC_NRNRB_specs_1;
asn_struct_free_f NRNRB_free;
asn_struct_print_f NRNRB_print;
asn_constr_check_f NRNRB_constraint;
ber_type_decoder_f NRNRB_decode_ber;
der_type_encoder_f NRNRB_encode_der;
xer_type_decoder_f NRNRB_decode_xer;
xer_type_encoder_f NRNRB_encode_xer;
oer_type_decoder_f NRNRB_decode_oer;
oer_type_encoder_f NRNRB_encode_oer;
per_type_decoder_f NRNRB_decode_uper;
per_type_encoder_f NRNRB_encode_uper;
per_type_decoder_f NRNRB_decode_aper;
per_type_encoder_f NRNRB_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_NRNRB_H_ */
#include <asn_internal.h>
