/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_MDTMode-NR.h"

#include "ASN_XNAP_ImmediateMDT-NR.h"
#include "ASN_XNAP_LoggedMDT-NR.h"
#include "ASN_XNAP_MDTMode-NR-Extension.h"
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_MDTMode_NR_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ASN_XNAP_MDTMode_NR_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_XNAP_MDTMode_NR_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_MDTMode_NR, choice.immediateMDT),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ImmediateMDT_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"immediateMDT"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_MDTMode_NR, choice.loggedMDT),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_LoggedMDT_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"loggedMDT"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_MDTMode_NR, choice.mDTMode_NR_Extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_MDTMode_NR_Extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mDTMode-NR-Extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_MDTMode_NR_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* immediateMDT */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* loggedMDT */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* mDTMode-NR-Extension */
};
asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_MDTMode_NR_specs_1 = {
	sizeof(struct ASN_XNAP_MDTMode_NR),
	offsetof(struct ASN_XNAP_MDTMode_NR, _asn_ctx),
	offsetof(struct ASN_XNAP_MDTMode_NR, present),
	sizeof(((struct ASN_XNAP_MDTMode_NR *)0)->present),
	asn_MAP_ASN_XNAP_MDTMode_NR_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_MDTMode_NR = {
	"MDTMode-NR",
	"MDTMode-NR",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ASN_XNAP_MDTMode_NR_constr_1, &asn_PER_type_ASN_XNAP_MDTMode_NR_constr_1, CHOICE_constraint },
	asn_MBR_ASN_XNAP_MDTMode_NR_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_MDTMode_NR_specs_1	/* Additional specs */
};

