/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_QoSFlowLevelQoSParameters.h"

#include "ASN_XNAP_GBRQoSFlowInfo.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_additionalQoSflowInfo_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_additionalQoSflowInfo_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_XNAP_additionalQoSflowInfo_value2enum_6[] = {
	{ 0,	11,	"more-likely" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ASN_XNAP_additionalQoSflowInfo_enum2value_6[] = {
	0	/* more-likely(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_additionalQoSflowInfo_specs_6 = {
	asn_MAP_ASN_XNAP_additionalQoSflowInfo_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_XNAP_additionalQoSflowInfo_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_additionalQoSflowInfo_6 = {
	"additionalQoSflowInfo",
	"additionalQoSflowInfo",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6,
	sizeof(asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6)
		/sizeof(asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6[0]) - 1, /* 1 */
	asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6)
		/sizeof(asn_DEF_ASN_XNAP_additionalQoSflowInfo_tags_6[0]), /* 2 */
	{ &asn_OER_type_ASN_XNAP_additionalQoSflowInfo_constr_6, &asn_PER_type_ASN_XNAP_additionalQoSflowInfo_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_XNAP_additionalQoSflowInfo_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_QoSFlowLevelQoSParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, qos_characteristics),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_QoSCharacteristics,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qos-characteristics"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, allocationAndRetentionPrio),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_AllocationandRetentionPriority,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allocationAndRetentionPrio"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, gBRQoSFlowInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_GBRQoSFlowInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gBRQoSFlowInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, reflectiveQoS),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ReflectiveQoSAttribute,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reflectiveQoS"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, additionalQoSflowInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_additionalQoSflowInfo_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalQoSflowInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P277,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_QoSFlowLevelQoSParameters_oms_1[] = { 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_QoSFlowLevelQoSParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* qos-characteristics */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* allocationAndRetentionPrio */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gBRQoSFlowInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* reflectiveQoS */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* additionalQoSflowInfo */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_QoSFlowLevelQoSParameters_specs_1 = {
	sizeof(struct ASN_XNAP_QoSFlowLevelQoSParameters),
	offsetof(struct ASN_XNAP_QoSFlowLevelQoSParameters, _asn_ctx),
	asn_MAP_ASN_XNAP_QoSFlowLevelQoSParameters_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_QoSFlowLevelQoSParameters_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters = {
	"QoSFlowLevelQoSParameters",
	"QoSFlowLevelQoSParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1,
	sizeof(asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_QoSFlowLevelQoSParameters_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_QoSFlowLevelQoSParameters_1,
	6,	/* Elements count */
	&asn_SPC_ASN_XNAP_QoSFlowLevelQoSParameters_specs_1	/* Additional specs */
};

