/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_LoggedMDT_NR_H_
#define	_ASN_XNAP_LoggedMDT_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_LoggingInterval.h"
#include "ASN_XNAP_LoggingDuration.h"
#include "ASN_XNAP_ReportType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_BluetoothMeasurementConfiguration;
struct ASN_XNAP_WLANMeasurementConfiguration;
struct ASN_XNAP_SensorMeasurementConfiguration;
struct ASN_XNAP_AreaScopeOfNeighCellsList;
struct ASN_XNAP_ProtocolExtensionContainer;

/* ASN_XNAP_LoggedMDT-NR */
typedef struct ASN_XNAP_LoggedMDT_NR {
	ASN_XNAP_LoggingInterval_t	 loggingInterval;
	ASN_XNAP_LoggingDuration_t	 loggingDuration;
	ASN_XNAP_ReportType_t	 reportType;
	struct ASN_XNAP_BluetoothMeasurementConfiguration	*bluetoothMeasurementConfiguration;	/* OPTIONAL */
	struct ASN_XNAP_WLANMeasurementConfiguration	*wLANMeasurementConfiguration;	/* OPTIONAL */
	struct ASN_XNAP_SensorMeasurementConfiguration	*sensorMeasurementConfiguration;	/* OPTIONAL */
	struct ASN_XNAP_AreaScopeOfNeighCellsList	*areaScopeOfNeighCellsList;	/* OPTIONAL */
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_LoggedMDT_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_LoggedMDT_NR;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_LoggedMDT_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_LoggedMDT_NR_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_LoggedMDT_NR_H_ */
#include <asn_internal.h>
