/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_CellMeasurementResult-Item.h"

#include "ASN_XNAP_RadioResourceStatus.h"
#include "ASN_XNAP_TNLCapacityIndicator.h"
#include "ASN_XNAP_CompositeAvailableCapacityGroup.h"
#include "ASN_XNAP_SliceAvailableCapacity.h"
#include "ASN_XNAP_RRCConnections.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_CellMeasurementResult_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, cell_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_GlobalNG_RANCell_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-ID"
		},
	{ ATF_POINTER, 7, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, radioResourceStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RadioResourceStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioResourceStatus"
		},
	{ ATF_POINTER, 6, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, tNLCapacityIndicator),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_TNLCapacityIndicator,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tNLCapacityIndicator"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, compositeAvailableCapacityGroup),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_CompositeAvailableCapacityGroup,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compositeAvailableCapacityGroup"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, sliceAvailableCapacity),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_SliceAvailableCapacity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sliceAvailableCapacity"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, numberofActiveUEs),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_NumberofActiveUEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberofActiveUEs"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, rRCConnections),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_RRCConnections,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRCConnections"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_CellMeasurementResult_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P34,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_CellMeasurementResult_Item_oms_1[] = { 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_CellMeasurementResult_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cell-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radioResourceStatus */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tNLCapacityIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* compositeAvailableCapacityGroup */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sliceAvailableCapacity */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* numberofActiveUEs */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rRCConnections */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_CellMeasurementResult_Item_specs_1 = {
	sizeof(struct ASN_XNAP_CellMeasurementResult_Item),
	offsetof(struct ASN_XNAP_CellMeasurementResult_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_CellMeasurementResult_Item_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_CellMeasurementResult_Item_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_CellMeasurementResult_Item = {
	"CellMeasurementResult-Item",
	"CellMeasurementResult-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_CellMeasurementResult_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_CellMeasurementResult_Item_1,
	8,	/* Elements count */
	&asn_SPC_ASN_XNAP_CellMeasurementResult_Item_specs_1	/* Additional specs */
};

