/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_SpecialSubframeInfo-E-UTRA.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_SpecialSubframeInfo_E_UTRA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA, specialSubframePattern),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_SpecialSubframePatterns_E_UTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"specialSubframePattern"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA, cyclicPrefixDL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_CyclicPrefix_E_UTRA_DL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cyclicPrefixDL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA, cyclicPrefixUL),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_CyclicPrefix_E_UTRA_UL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cyclicPrefixUL"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P344,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_SpecialSubframeInfo_E_UTRA_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* specialSubframePattern */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cyclicPrefixDL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cyclicPrefixUL */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SpecialSubframeInfo_E_UTRA_specs_1 = {
	sizeof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA),
	offsetof(struct ASN_XNAP_SpecialSubframeInfo_E_UTRA, _asn_ctx),
	asn_MAP_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_SpecialSubframeInfo_E_UTRA_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA = {
	"SpecialSubframeInfo-E-UTRA",
	"SpecialSubframeInfo-E-UTRA",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SpecialSubframeInfo_E_UTRA_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_SpecialSubframeInfo_E_UTRA_1,
	4,	/* Elements count */
	&asn_SPC_ASN_XNAP_SpecialSubframeInfo_E_UTRA_specs_1	/* Additional specs */
};

