/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_NG_eNB_RadioResourceStatus_H_
#define	_ASN_XNAP_NG_eNB_RadioResourceStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_DL-GBR-PRB-usage.h"
#include "ASN_XNAP_UL-GBR-PRB-usage.h"
#include "ASN_XNAP_DL-non-GBR-PRB-usage.h"
#include "ASN_XNAP_UL-non-GBR-PRB-usage.h"
#include "ASN_XNAP_DL-Total-PRB-usage.h"
#include "ASN_XNAP_UL-Total-PRB-usage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* ASN_XNAP_NG-eNB-RadioResourceStatus */
typedef struct ASN_XNAP_NG_eNB_RadioResourceStatus {
	ASN_XNAP_DL_GBR_PRB_usage_t	 dL_GBR_PRB_usage;
	ASN_XNAP_UL_GBR_PRB_usage_t	 uL_GBR_PRB_usage;
	ASN_XNAP_DL_non_GBR_PRB_usage_t	 dL_non_GBR_PRB_usage;
	ASN_XNAP_UL_non_GBR_PRB_usage_t	 uL_non_GBR_PRB_usage;
	ASN_XNAP_DL_Total_PRB_usage_t	 dL_Total_PRB_usage;
	ASN_XNAP_UL_Total_PRB_usage_t	 uL_Total_PRB_usage;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_NG_eNB_RadioResourceStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NG_eNB_RadioResourceStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_NG_eNB_RadioResourceStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_NG_eNB_RadioResourceStatus_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_NG_eNB_RadioResourceStatus_H_ */
#include <asn_internal.h>
