/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_NPRACHConfiguration.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
#include "ASN_XNAP_NPRACHConfiguration-FDD.h"
#include "ASN_XNAP_NPRACHConfiguration-TDD.h"
#include "ASN_XNAP_ProtocolIE-Single-Container.h"
static asn_oer_constraints_t asn_OER_type_ASN_XNAP_fdd_or_tdd_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ASN_XNAP_fdd_or_tdd_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_XNAP_fdd_or_tdd_2[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_NPRACHConfiguration_FDD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_NPRACHConfiguration_TDD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolIE_Single_Container_121P36,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_fdd_or_tdd_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tdd */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_fdd_or_tdd_specs_2 = {
	sizeof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd),
	offsetof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd, _asn_ctx),
	offsetof(struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd, present),
	sizeof(((struct ASN_XNAP_NPRACHConfiguration__fdd_or_tdd *)0)->present),
	asn_MAP_ASN_XNAP_fdd_or_tdd_tag2el_2,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_fdd_or_tdd_2 = {
	"fdd-or-tdd",
	"fdd-or-tdd",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ASN_XNAP_fdd_or_tdd_constr_2, &asn_PER_type_ASN_XNAP_fdd_or_tdd_constr_2, CHOICE_constraint },
	asn_MBR_ASN_XNAP_fdd_or_tdd_2,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_fdd_or_tdd_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_NPRACHConfiguration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_NPRACHConfiguration, fdd_or_tdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_fdd_or_tdd_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fdd-or-tdd"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_NPRACHConfiguration, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P201,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_NPRACHConfiguration_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_NPRACHConfiguration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-or-tdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_NPRACHConfiguration_specs_1 = {
	sizeof(struct ASN_XNAP_NPRACHConfiguration),
	offsetof(struct ASN_XNAP_NPRACHConfiguration, _asn_ctx),
	asn_MAP_ASN_XNAP_NPRACHConfiguration_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_NPRACHConfiguration_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_NPRACHConfiguration = {
	"NPRACHConfiguration",
	"NPRACHConfiguration",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1,
	sizeof(asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_NPRACHConfiguration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_NPRACHConfiguration_1,
	2,	/* Elements count */
	&asn_SPC_ASN_XNAP_NPRACHConfiguration_specs_1	/* Additional specs */
};

