/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_SSBAreaRadioResourceStatus-List-Item.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
static int
memb_ASN_XNAP_sSBIndex_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 63)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_sSBIndex_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..63) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_sSBIndex_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  63 }	/* (0..63) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, sSBIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ASN_XNAP_sSBIndex_constr_2, &asn_PER_memb_ASN_XNAP_sSBIndex_constr_2,  memb_ASN_XNAP_sSBIndex_constraint_1 },
		0, 0, /* No default value */
		"sSBIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_DL_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_GBR_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-DL-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_UL_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_GBR_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-UL-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_dL_non_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_non_GBR_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-dL-non-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_uL_non_GBR_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_non_GBR_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-uL-non-GBR-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_dL_Total_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_DL_Total_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-dL-Total-PRB-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, ssb_Area_uL_Total_PRB_usage),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_UL_Total_PRB_usage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-Area-uL-Total-PRB-usage"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P346,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_oms_1[] = { 7 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sSBIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssb-Area-DL-GBR-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ssb-Area-UL-GBR-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ssb-Area-dL-non-GBR-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ssb-Area-uL-non-GBR-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ssb-Area-dL-Total-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ssb-Area-uL-Total-PRB-usage */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_specs_1 = {
	sizeof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item),
	offsetof(struct ASN_XNAP_SSBAreaRadioResourceStatus_List_Item, _asn_ctx),
	asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item = {
	"SSBAreaRadioResourceStatus-List-Item",
	"SSBAreaRadioResourceStatus-List-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_1,
	8,	/* Elements count */
	&asn_SPC_ASN_XNAP_SSBAreaRadioResourceStatus_List_Item_specs_1	/* Additional specs */
};

