/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_MobilityParametersInformation.h"

static int
memb_ASN_XNAP_handoverTriggerChange_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -20 && value <= 20)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_handoverTriggerChange_constr_2 CC_NOTUSED = {
	{ 1, 0 }	/* (-20..20) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_handoverTriggerChange_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6, -20,  20 }	/* (-20..20) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_XNAP_MobilityParametersInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_MobilityParametersInformation, handoverTriggerChange),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ASN_XNAP_handoverTriggerChange_constr_2, &asn_PER_memb_ASN_XNAP_handoverTriggerChange_constr_2,  memb_ASN_XNAP_handoverTriggerChange_constraint_1 },
		0, 0, /* No default value */
		"handoverTriggerChange"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_MobilityParametersInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* handoverTriggerChange */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_MobilityParametersInformation_specs_1 = {
	sizeof(struct ASN_XNAP_MobilityParametersInformation),
	offsetof(struct ASN_XNAP_MobilityParametersInformation, _asn_ctx),
	asn_MAP_ASN_XNAP_MobilityParametersInformation_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_MobilityParametersInformation = {
	"MobilityParametersInformation",
	"MobilityParametersInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1,
	sizeof(asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_MobilityParametersInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_MobilityParametersInformation_1,
	1,	/* Elements count */
	&asn_SPC_ASN_XNAP_MobilityParametersInformation_specs_1	/* Additional specs */
};

