/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#ifndef	_ASN_XNAP_Non_AnchorCarrierFrequencylist_H_
#define	_ASN_XNAP_Non_AnchorCarrierFrequencylist_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct ASN_XNAP_Non_AnchorCarrierFrequencylist__Member {
	OCTET_STRING_t	 non_anchorCarrierFrquency;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Non_AnchorCarrierFrequencylist__Member;

/* ASN_XNAP_Non-AnchorCarrierFrequencylist */
typedef struct ASN_XNAP_Non_AnchorCarrierFrequencylist {
	A_SEQUENCE_OF(Non_AnchorCarrierFrequencylist__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_Non_AnchorCarrierFrequencylist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_Non_AnchorCarrierFrequencylist;
extern asn_SET_OF_specifics_t asn_SPC_ASN_XNAP_Non_AnchorCarrierFrequencylist_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_XNAP_Non_AnchorCarrierFrequencylist_1[1];
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_Non_AnchorCarrierFrequencylist_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_XNAP_Non_AnchorCarrierFrequencylist_H_ */
#include <asn_internal.h>
