/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_TNLCapacityIndicator.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_TNLCapacityIndicator_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TNLCapacityIndicator, dLTNLOfferedCapacity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_OfferedCapacity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dLTNLOfferedCapacity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TNLCapacityIndicator, dLTNLAvailableCapacity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_AvailableCapacity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dLTNLAvailableCapacity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TNLCapacityIndicator, uLTNLOfferedCapacity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_OfferedCapacity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uLTNLOfferedCapacity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_TNLCapacityIndicator, uLTNLAvailableCapacity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_AvailableCapacity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uLTNLAvailableCapacity"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_TNLCapacityIndicator, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P192,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_TNLCapacityIndicator_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_TNLCapacityIndicator_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dLTNLOfferedCapacity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dLTNLAvailableCapacity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uLTNLOfferedCapacity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uLTNLAvailableCapacity */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_TNLCapacityIndicator_specs_1 = {
	sizeof(struct ASN_XNAP_TNLCapacityIndicator),
	offsetof(struct ASN_XNAP_TNLCapacityIndicator, _asn_ctx),
	asn_MAP_ASN_XNAP_TNLCapacityIndicator_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_TNLCapacityIndicator_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_TNLCapacityIndicator = {
	"TNLCapacityIndicator",
	"TNLCapacityIndicator",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1,
	sizeof(asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_TNLCapacityIndicator_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_TNLCapacityIndicator_1,
	5,	/* Elements count */
	&asn_SPC_ASN_XNAP_TNLCapacityIndicator_specs_1	/* Additional specs */
};

