/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "../xnap_asn.1/XnAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_RRCReestab-Initiated-Reporting-wo-UERLFReport.h"

#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, failureCellPCI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_NG_RAN_CellPCI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"failureCellPCI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, reestabCellCGI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_GlobalNG_RANCell_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reestabCellCGI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, c_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_C_RNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"c-RNTI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, shortMAC_I),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_MAC_I,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"shortMAC-I"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProtocolExtensionContainer_168P304,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* failureCellPCI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reestabCellCGI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* c-RNTI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* shortMAC-I */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_specs_1 = {
	sizeof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport),
	offsetof(struct ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport, _asn_ctx),
	asn_MAP_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport = {
	"RRCReestab-Initiated-Reporting-wo-UERLFReport",
	"RRCReestab-Initiated-Reporting-wo-UERLFReport",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1,
	sizeof(asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_1,
	5,	/* Elements count */
	&asn_SPC_ASN_XNAP_RRCReestab_Initiated_Reporting_wo_UERLFReport_specs_1	/* Additional specs */
};

