/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Descriptions"
 * 	found in "../xnap_asn.1/XnAP-PDU-Descriptions.asn"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D ../xnap_src`
 */

#include "ASN_XNAP_SuccessfulOutcome.h"

static const long asn_VAL_1_ASN_XNAP_id_handoverPreparation = 0;
static const long asn_VAL_1_ASN_XNAP_reject = 0;
static const long asn_VAL_2_ASN_XNAP_id_retrieveUEContext = 3;
static const long asn_VAL_2_ASN_XNAP_reject = 0;
static const long asn_VAL_3_ASN_XNAP_id_sNGRANnodeAdditionPreparation = 7;
static const long asn_VAL_3_ASN_XNAP_reject = 0;
static const long asn_VAL_4_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation = 9;
static const long asn_VAL_4_ASN_XNAP_reject = 0;
static const long asn_VAL_5_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation = 10;
static const long asn_VAL_5_ASN_XNAP_reject = 0;
static const long asn_VAL_6_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeRelease = 11;
static const long asn_VAL_6_ASN_XNAP_reject = 0;
static const long asn_VAL_7_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeRelease = 12;
static const long asn_VAL_7_ASN_XNAP_reject = 0;
static const long asn_VAL_8_ASN_XNAP_id_sNGRANnodeChange = 14;
static const long asn_VAL_8_ASN_XNAP_reject = 0;
static const long asn_VAL_9_ASN_XNAP_id_xnRemoval = 16;
static const long asn_VAL_9_ASN_XNAP_reject = 0;
static const long asn_VAL_10_ASN_XNAP_id_xnSetup = 17;
static const long asn_VAL_10_ASN_XNAP_reject = 0;
static const long asn_VAL_11_ASN_XNAP_id_nGRANnodeConfigurationUpdate = 18;
static const long asn_VAL_11_ASN_XNAP_reject = 0;
static const long asn_VAL_12_ASN_XNAP_id_e_UTRA_NR_CellResourceCoordination = 25;
static const long asn_VAL_12_ASN_XNAP_reject = 0;
static const long asn_VAL_13_ASN_XNAP_id_cellActivation = 19;
static const long asn_VAL_13_ASN_XNAP_reject = 0;
static const long asn_VAL_14_ASN_XNAP_id_reset = 20;
static const long asn_VAL_14_ASN_XNAP_reject = 0;
static const long asn_VAL_15_ASN_XNAP_id_resourceStatusReportingInitiation = 34;
static const long asn_VAL_15_ASN_XNAP_reject = 0;
static const long asn_VAL_16_ASN_XNAP_id_mobilitySettingsChange = 36;
static const long asn_VAL_16_ASN_XNAP_reject = 0;
static const long asn_VAL_17_ASN_XNAP_id_iABTransportMigrationManagement = 44;
static const long asn_VAL_17_ASN_XNAP_reject = 0;
static const long asn_VAL_18_ASN_XNAP_id_iABTransportMigrationModification = 45;
static const long asn_VAL_18_ASN_XNAP_reject = 0;
static const long asn_VAL_19_ASN_XNAP_id_iABResourceCoordination = 46;
static const long asn_VAL_19_ASN_XNAP_reject = 0;
static const long asn_VAL_20_ASN_XNAP_id_partialUEContextTransfer = 49;
static const long asn_VAL_20_ASN_XNAP_reject = 0;
static const long asn_VAL_21_ASN_XNAP_id_sNStatusTransfer = 1;
static const long asn_VAL_21_ASN_XNAP_ignore = 1;
static const long asn_VAL_22_ASN_XNAP_id_handoverCancel = 2;
static const long asn_VAL_22_ASN_XNAP_ignore = 1;
static const long asn_VAL_23_ASN_XNAP_id_rANPaging = 4;
static const long asn_VAL_23_ASN_XNAP_reject = 0;
static const long asn_VAL_24_ASN_XNAP_id_xnUAddressIndication = 5;
static const long asn_VAL_24_ASN_XNAP_reject = 0;
static const long asn_VAL_25_ASN_XNAP_id_uEContextRelease = 6;
static const long asn_VAL_25_ASN_XNAP_reject = 0;
static const long asn_VAL_26_ASN_XNAP_id_sNGRANnodeReconfigurationCompletion = 8;
static const long asn_VAL_26_ASN_XNAP_reject = 0;
static const long asn_VAL_27_ASN_XNAP_id_sNGRANnodeCounterCheck = 13;
static const long asn_VAL_27_ASN_XNAP_reject = 0;
static const long asn_VAL_28_ASN_XNAP_id_rRCTransfer = 15;
static const long asn_VAL_28_ASN_XNAP_reject = 0;
static const long asn_VAL_29_ASN_XNAP_id_errorIndication = 21;
static const long asn_VAL_29_ASN_XNAP_ignore = 1;
static const long asn_VAL_30_ASN_XNAP_id_privateMessage = 22;
static const long asn_VAL_30_ASN_XNAP_ignore = 1;
static const long asn_VAL_31_ASN_XNAP_id_notificationControl = 23;
static const long asn_VAL_31_ASN_XNAP_ignore = 1;
static const long asn_VAL_32_ASN_XNAP_id_activityNotification = 24;
static const long asn_VAL_32_ASN_XNAP_ignore = 1;
static const long asn_VAL_33_ASN_XNAP_id_secondaryRATDataUsageReport = 26;
static const long asn_VAL_33_ASN_XNAP_reject = 0;
static const long asn_VAL_34_ASN_XNAP_id_deactivateTrace = 27;
static const long asn_VAL_34_ASN_XNAP_ignore = 1;
static const long asn_VAL_35_ASN_XNAP_id_traceStart = 28;
static const long asn_VAL_35_ASN_XNAP_ignore = 1;
static const long asn_VAL_36_ASN_XNAP_id_handoverSuccess = 29;
static const long asn_VAL_36_ASN_XNAP_ignore = 1;
static const long asn_VAL_37_ASN_XNAP_id_conditionalHandoverCancel = 30;
static const long asn_VAL_37_ASN_XNAP_ignore = 1;
static const long asn_VAL_38_ASN_XNAP_id_earlyStatusTransfer = 31;
static const long asn_VAL_38_ASN_XNAP_ignore = 1;
static const long asn_VAL_39_ASN_XNAP_id_failureIndication = 32;
static const long asn_VAL_39_ASN_XNAP_ignore = 1;
static const long asn_VAL_40_ASN_XNAP_id_handoverReport = 33;
static const long asn_VAL_40_ASN_XNAP_ignore = 1;
static const long asn_VAL_41_ASN_XNAP_id_resourceStatusReporting = 35;
static const long asn_VAL_41_ASN_XNAP_ignore = 1;
static const long asn_VAL_42_ASN_XNAP_id_accessAndMobilityIndication = 37;
static const long asn_VAL_42_ASN_XNAP_ignore = 1;
static const long asn_VAL_43_ASN_XNAP_id_cellTrafficTrace = 38;
static const long asn_VAL_43_ASN_XNAP_ignore = 1;
static const long asn_VAL_44_ASN_XNAP_id_RANMulticastGroupPaging = 39;
static const long asn_VAL_44_ASN_XNAP_reject = 0;
static const long asn_VAL_45_ASN_XNAP_id_scgFailureInformationReport = 40;
static const long asn_VAL_45_ASN_XNAP_ignore = 1;
static const long asn_VAL_46_ASN_XNAP_id_scgFailureTransfer = 42;
static const long asn_VAL_46_ASN_XNAP_ignore = 1;
static const long asn_VAL_47_ASN_XNAP_id_f1CTrafficTransfer = 43;
static const long asn_VAL_47_ASN_XNAP_reject = 0;
static const long asn_VAL_48_ASN_XNAP_id_retrieveUEContextConfirm = 47;
static const long asn_VAL_48_ASN_XNAP_ignore = 1;
static const long asn_VAL_49_ASN_XNAP_id_cPCCancel = 48;
static const long asn_VAL_49_ASN_XNAP_ignore = 1;
static const asn_ioc_cell_t asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_HandoverRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_1_ASN_XNAP_id_handoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_1_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_2_ASN_XNAP_id_retrieveUEContext },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_2_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_3_ASN_XNAP_id_sNGRANnodeAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_3_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_4_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_4_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_5_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_5_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_6_ASN_XNAP_id_mNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_6_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeReleaseConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_7_ASN_XNAP_id_sNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_7_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_SNodeChangeRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_8_ASN_XNAP_id_sNGRANnodeChange },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_8_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnRemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_9_ASN_XNAP_id_xnRemoval },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_9_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnSetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_XnSetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_10_ASN_XNAP_id_xnSetup },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_10_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_11_ASN_XNAP_id_nGRANnodeConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_11_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_12_ASN_XNAP_id_e_UTRA_NR_CellResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_12_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CellActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_CellActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_CellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_13_ASN_XNAP_id_cellActivation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_13_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResetRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResetResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_14_ASN_XNAP_id_reset },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_14_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_15_ASN_XNAP_id_resourceStatusReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_15_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_MobilityChangeFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_16_ASN_XNAP_id_mobilitySettingsChange },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_16_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationManagementReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_17_ASN_XNAP_id_iABTransportMigrationManagement },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_17_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABTransportMigrationModificationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_18_ASN_XNAP_id_iABTransportMigrationModification },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_18_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_IABResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_IABResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_19_ASN_XNAP_id_iABResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_19_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransfer },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransferAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_ASN_XNAP_PartialUEContextTransferFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_20_ASN_XNAP_id_partialUEContextTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_20_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_21_ASN_XNAP_id_sNStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_21_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_22_ASN_XNAP_id_handoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_22_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RANPaging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_23_ASN_XNAP_id_rANPaging },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_23_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_XnUAddressIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_24_ASN_XNAP_id_xnUAddressIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_24_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_UEContextRelease },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_25_ASN_XNAP_id_uEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_25_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeReconfigurationComplete },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_26_ASN_XNAP_id_sNGRANnodeReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_26_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SNodeCounterCheckRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_27_ASN_XNAP_id_sNGRANnodeCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_27_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RRCTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_28_ASN_XNAP_id_rRCTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_28_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_29_ASN_XNAP_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_29_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_30_ASN_XNAP_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_30_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_NotificationControlIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_31_ASN_XNAP_id_notificationControl },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_31_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ActivityNotification },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_32_ASN_XNAP_id_activityNotification },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_32_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_SecondaryRATDataUsageReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_33_ASN_XNAP_id_secondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_33_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_DeactivateTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_34_ASN_XNAP_id_deactivateTrace },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_34_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_TraceStart },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_35_ASN_XNAP_id_traceStart },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_35_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverSuccess },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_36_ASN_XNAP_id_handoverSuccess },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_36_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ConditionalHandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_37_ASN_XNAP_id_conditionalHandoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_37_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_EarlyStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_38_ASN_XNAP_id_earlyStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_38_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_FailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_39_ASN_XNAP_id_failureIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_39_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_HandoverReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_40_ASN_XNAP_id_handoverReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_40_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ResourceStatusUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_41_ASN_XNAP_id_resourceStatusReporting },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_41_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_AccessAndMobilityIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_42_ASN_XNAP_id_accessAndMobilityIndication },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_42_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CellTrafficTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_43_ASN_XNAP_id_cellTrafficTrace },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_43_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RANMulticastGroupPaging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_44_ASN_XNAP_id_RANMulticastGroupPaging },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_44_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ScgFailureInformationReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_45_ASN_XNAP_id_scgFailureInformationReport },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_45_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_ScgFailureTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_46_ASN_XNAP_id_scgFailureTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_46_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_F1CTrafficTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_47_ASN_XNAP_id_f1CTrafficTransfer },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_47_ASN_XNAP_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_RetrieveUEContextConfirm },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_48_ASN_XNAP_id_retrieveUEContextConfirm },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_48_ASN_XNAP_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_ASN_XNAP_CPCCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ASN_XNAP_ProcedureCode, &asn_VAL_49_ASN_XNAP_id_cPCCancel },
	{ "&criticality", aioc__value, &asn_DEF_ASN_XNAP_Criticality, &asn_VAL_49_ASN_XNAP_ignore }
};
static const asn_ioc_set_t asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1[] = {
	{ 49, 5, asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_ASN_XNAP_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SuccessfulOutcome_ASN_XNAP_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct ASN_XNAP_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_ASN_XNAP_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_SuccessfulOutcome_ASN_XNAP_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_ASN_XNAP_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 1; /* &SuccessfulOutcome */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct ASN_XNAP_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_ASN_XNAP_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_procedureCode_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_criticality_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ASN_XNAP_value_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_ASN_XNAP_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_XNAP_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.HandoverRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_HandoverRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.RetrieveUEContextResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_RetrieveUEContextResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RetrieveUEContextResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeAdditionRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeAdditionRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeAdditionRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeModificationRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeModificationRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeModificationRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeModificationConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeModificationConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeModificationConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeReleaseRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeReleaseRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeReleaseRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeReleaseConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeReleaseConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeReleaseConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.SNodeChangeConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_SNodeChangeConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNodeChangeConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.XnRemovalResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_XnRemovalResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnRemovalResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.XnSetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_XnSetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnSetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.NGRANNodeConfigurationUpdateAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_NGRANNodeConfigurationUpdateAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"NGRANNodeConfigurationUpdateAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.E_UTRA_NR_CellResourceCoordinationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_E_UTRA_NR_CellResourceCoordinationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-UTRA-NR-CellResourceCoordinationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.CellActivationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_CellActivationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellActivationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.ResetResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ResetResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResetResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.ResourceStatusResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_ResourceStatusResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.MobilityChangeAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_MobilityChangeAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"MobilityChangeAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.IABTransportMigrationManagementResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABTransportMigrationManagementResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABTransportMigrationManagementResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.IABTransportMigrationModificationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABTransportMigrationModificationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABTransportMigrationModificationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.IABResourceCoordinationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_IABResourceCoordinationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"IABResourceCoordinationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome__value, choice.PartialUEContextTransferAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ASN_XNAP_PartialUEContextTransferAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PartialUEContextTransferAcknowledge"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 19 }, /* HandoverRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 18 }, /* RetrieveUEContextResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 17 }, /* SNodeAdditionRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 16 }, /* SNodeModificationRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 15 }, /* SNodeModificationConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 14 }, /* SNodeReleaseRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 13 }, /* SNodeReleaseConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 12 }, /* SNodeChangeConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 11 }, /* XnRemovalResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 10 }, /* XnSetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 9 }, /* NGRANNodeConfigurationUpdateAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 8 }, /* E-UTRA-NR-CellResourceCoordinationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 7 }, /* CellActivationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 6 }, /* ResetResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 5 }, /* ResourceStatusResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 4 }, /* MobilityChangeAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 3 }, /* IABTransportMigrationManagementResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 2 }, /* IABTransportMigrationModificationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 1 }, /* IABResourceCoordinationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 0 } /* PartialUEContextTransferAcknowledge */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_XNAP_value_specs_4 = {
	sizeof(struct ASN_XNAP_SuccessfulOutcome__value),
	offsetof(struct ASN_XNAP_SuccessfulOutcome__value, _asn_ctx),
	offsetof(struct ASN_XNAP_SuccessfulOutcome__value, present),
	sizeof(((struct ASN_XNAP_SuccessfulOutcome__value *)0)->present),
	asn_MAP_ASN_XNAP_value_tag2el_4,
	20,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_ASN_XNAP_value_4,
	20,	/* Elements count */
	&asn_SPC_ASN_XNAP_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_XNAP_SuccessfulOutcome_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_ProcedureCode,
		0,
		{ &asn_OER_memb_ASN_XNAP_procedureCode_constr_2, &asn_PER_memb_ASN_XNAP_procedureCode_constr_2,  memb_ASN_XNAP_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_Criticality,
		select_SuccessfulOutcome_ASN_XNAP_criticality_type,
		{ &asn_OER_memb_ASN_XNAP_criticality_constr_3, &asn_PER_memb_ASN_XNAP_criticality_constr_3,  memb_ASN_XNAP_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct ASN_XNAP_SuccessfulOutcome, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_XNAP_value_4,
		select_SuccessfulOutcome_ASN_XNAP_value_type,
		{ &asn_OER_memb_ASN_XNAP_value_constr_4, &asn_PER_memb_ASN_XNAP_value_constr_4,  memb_ASN_XNAP_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_XNAP_SuccessfulOutcome_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_XNAP_SuccessfulOutcome_specs_1 = {
	sizeof(struct ASN_XNAP_SuccessfulOutcome),
	offsetof(struct ASN_XNAP_SuccessfulOutcome, _asn_ctx),
	asn_MAP_ASN_XNAP_SuccessfulOutcome_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SuccessfulOutcome = {
	"SuccessfulOutcome",
	"SuccessfulOutcome",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1,
	sizeof(asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1[0]), /* 1 */
	asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_ASN_XNAP_SuccessfulOutcome_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_XNAP_SuccessfulOutcome_1,
	3,	/* Elements count */
	&asn_SPC_ASN_XNAP_SuccessfulOutcome_specs_1	/* Additional specs */
};

